# Generated by Django 6.0.3 on 2026-04-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_question_options_question_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True or False'), ('identification', 'Identification'), ('essay', 'Essay / Short Answer'), ('oral', 'Oral / Discussion')], default='multiple_choice', max_length=20),
        ),
    ]
