# Generated by Django 6.0.3 on 2026-04-03 04:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonplan',
            options={'ordering': ['week_number', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tableofspecifications',
            options={'ordering': ['-created_at'], 'verbose_name': 'Table of Specifications', 'verbose_name_plural': 'Tables of Specifications'},
        ),
        migrations.RenameField(
            model_name='lessonplan',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='ai_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='error_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Generating…'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tableofspecifications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableofspecifications',
            name='error_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tableofspecifications',
            name='status',
            field=models.CharField(choices=[('pending', 'Generating…'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tableofspecifications',
            name='topics_data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='accounts.course'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tableofspecifications',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_list', to='accounts.course'),
        ),
        migrations.AlterField(
            model_name='tableofspecifications',
            name='tos_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
