# Generated by Django 6.0.3 on 2026-04-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_alter_lessonplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Generating…'), ('blueprint_pending', 'Blueprint Ready for Review'), ('blueprint_approved', 'Generating Presentation…'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
