# Generated by Django 4.2.30 on 2026-04-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0004_remove_tableofspecifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonplan',
            options={'managed': False, 'ordering': ['week_number', '-created_at']},
        ),
    ]
