# Generated by Django 4.2.7 on 2026-04-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0005_alter_lessonplan_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lessonplan',
            table='lessons_lessonplan',
        ),
    ]
