# Generated by Django 6.0.3 on 2026-04-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, help_text='Upload your course syllabus (.pdf or .docx)', upload_to='course_syllabus/'),
        ),
    ]
