# Generated by Django 6.0.3 on 2026-04-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_course_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='course',
            name='units',
        ),
        migrations.AddField(
            model_name='course',
            name='clos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='credit_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='error_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pending', 'Processing…'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_file',
            field=models.FileField(blank=True, upload_to='syllabi/'),
        ),
        migrations.AddField(
            model_name='course',
            name='weekly_plan',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
