# Generated by Django 6.0.3 on 2026-04-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_course_syllabus_remove_course_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pending', 'Processing…'), ('draft', 'Draft — Review Required'), ('confirmed', 'Confirmed'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
