# Generated by Django 6.0.3 on 2026-04-12 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_student_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roster_instructors',
            field=models.ManyToManyField(blank=True, related_name='student_roster', to=settings.AUTH_USER_MODEL),
        ),
    ]
