# Generated by Django 4.2.7 on 2026-04-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_course_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cs_section_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_section_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='pt_section_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
