# Generated by Django 4.2.7 on 2026-04-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_course_cs_section_name_course_exam_section_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='activity_max_scores',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='ao_section_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='ao_weight',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='course',
            name='final_activity_max_scores',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='req_weight',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
