# Generated by Django 4.2.7 on 2026-04-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_course_activity_max_scores_course_ao_section_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['student__last_name', 'student__first_name']},
        ),
    ]
