# Generated by Django 6.0.3 on 2026-04-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graderecord',
            options={'ordering': ['enrollment__student__last_name']},
        ),
        migrations.RenameField(
            model_name='graderecord',
            old_name='project_score',
            new_name='requirement_score',
        ),
        migrations.AddField(
            model_name='graderecord',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='quiz_scores',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
