# Generated by Django 4.2.7 on 2026-04-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_graderecord_final_term_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='graderecord',
            name='activity_column_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='activity_scores',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='final_activity_column_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='final_activity_scores',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
