# Generated by Django 6.0.3 on 2026-04-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
